services:
  pypass:
    container_name: pypass
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=DEBUG
    volumes:
      - ./screenshots:/app/screenshots # For screenshots when exception occurs
    ports:
      - "8193:8191"